### ISSUE TITLE
Add links to RDO dlrnapi dashboards 

### ISSUE THREAD

**Issue by halcyondude** [sshnaidm/sova#30]
Add links in sova to the dashboards at rdoproject.org

- https://dashboards.rdoproject.org/rdo-dev
- https://dashboards.rdoproject.org/master
- https://dashboards.rdoproject.org/pike
- https://dashboards.rdoproject.org/ocata

(coming soon)

- https://dashboards.rdoproject.org/queens

**Comment by halcyondude** [comment]
PR incoming that does this:
![screenshot-add-dashboard-links](https://user-images.githubusercontent.com/3286990/36508601-2dd6dedc-172b-11e8-826e-199ec7b9235d.png)

**Comment by halcyondude** [comment]
ok...i just learned a bunch about PR's made from forks, squashes, and rewriting git history.  fun!  this should be good to go now.

**Comment by sshnaidm** [comment]
merged
