### ISSUE TITLE
Add grids to HTML page

### ISSUE THREAD

**Issue by sshnaidm** [sshnaidm/sova#4]
Use bootstrap grids layout for HTML, replace tables with divs.

**Comment by eslynunez** [comment]
Hi! my name is Esly. I'm looking to contribute to an OS Project and I think I might have an idea for this. Ill pull and make a new branch called tablesplusplus. I will play around with header sorting as well.

**Comment by eslynunez** [comment]
Also @HarryRybacki sent me here.

**Comment by sshnaidm** [comment]
Hi, @eslynunez ! Welcome and thanks a lot for your contribution! :+1:

**Comment by sshnaidm** [comment]
Grids were added
